services:
  worker:
    container_name: allora-worker-1
    image: alloranetwork/allora-offchain-node:latest
    volumes:
      - ./worker-data:/data
    working_dir: /data
    env_file:
      - ./worker-data/env_file
    entrypoint: ["/node/allora_offchain_node"]
    networks:
      - mini191_default

networks:
  mini191_default:
    external: true

volumes:
  worker-data: {}

